/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package joysis_ams;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JAYCEE
 */
public class Student extends javax.swing.JFrame {
    static String viewqry;
    static String strDate ;
    static String studentid;
    
     public void qryDate(String Date){
         try{
            String db = "jdbc:mysql://localhost:3306/joysis_ams";
            Connection conn = DriverManager.getConnection(db, "root", null);
            String qry = "SELECT * FROM attendance WHERE date = ?";
            PreparedStatement ps = conn.prepareStatement(qry);
            ps.setString(1, Date);
            ResultSet rslt = ps.executeQuery();
            DefaultTableModel tbl = (DefaultTableModel)jtbl.getModel();
            tbl.setRowCount(0);
            while(rslt.next()){
                String date = rslt.getString("date");
                String stats = rslt.getString("status");
                String remarks = rslt.getString("remarks");
                
                String data[] = {date, stats, remarks};
                tbl.addRow(data);
            }
            
         }
         catch(Exception a){
            JOptionPane.showMessageDialog(null, a);
            a.printStackTrace();
         }
     }
     public void viewTable(String qry, String id){
          try{
            String db = "jdbc:mysql://localhost:3306/joysis_ams";
            Connection conn = DriverManager.getConnection(db, "root", null);
            PreparedStatement ps = conn.prepareStatement(qry);
            ps.setString(1, id);
            ResultSet rslt = ps.executeQuery();
            DefaultTableModel tbl = (DefaultTableModel)jtbl.getModel();
            tbl.setRowCount(0);
            while(rslt.next()){
                String date = rslt.getString("date");
                String stats = rslt.getString("status");
                String remarks = rslt.getString("remarks");
                
                String data[] = {date, stats, remarks};
                tbl.addRow(data);
            }
         }
         catch(Exception a){
            JOptionPane.showMessageDialog(null, a);
            a.printStackTrace();
         }

     }

     public void ComboBoxqry(){
        String selected = studentstatus.getSelectedItem().toString();
         switch(selected){
             case "Present":
                 viewqry = "SELECT * FROM attendance WHERE student_id = ? AND status = 'Present'";
                 break;
             case "Absent":
                 viewqry = "SELECT * FROM attendance  WHERE student_id = ? AND status = 'Absent'";
                 break;
                 
             case "Late":
                 viewqry = "SELECT * FROM attendance  WHERE student_id = ? AND status = 'Late'";
                 break;
                 
             default:
                 viewqry = "SELECT * FROM attendance  WHERE student_id = ?";
                 break;        
         }
     }
    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentName = new javax.swing.JLabel();
        studentId = new javax.swing.JLabel();
        studentSection = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl = new javax.swing.JTable();
        studentstatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentName.setText("Student Name");
        studentName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentNameMouseClicked(evt);
            }
        });
        jPanel1.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 22, -1, -1));

        studentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studentId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentId.setText("(Student ID)");
        jPanel1.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        studentSection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentSection.setText("Section");
        jPanel1.add(studentSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 22, -1, -1));

        jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Status", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl.setToolTipText("");
        jScrollPane1.setViewportView(jtbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 81, 779, 435));

        studentstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Present", "Late", "Absent" }));
        studentstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentstatusActionPerformed(evt);
            }
        });
        jPanel1.add(studentstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 50, 104, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jButton1.setText("Edit Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 130, 30));

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1 (1).png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 560));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        login lg = new login();
        ConnectionDB cdb = new ConnectionDB();
        String username = lg.username1;
        studentid = Integer.toString(cdb.id);
        cdb.getUsername(username);
        ComboBoxqry();
        viewTable(viewqry, studentid);
        studentName.setText(cdb.fname + " " + cdb.mname + " " + cdb.lname);
        studentId.setText(Integer.toString(cdb.id));
        studentSection.setText(cdb.sec);
     
    }//GEN-LAST:event_formWindowOpened

    private void studentNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameMouseClicked

    private void studentstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentstatusActionPerformed
        // TODO add your handling code here:
        login lg = new login();
        ConnectionDB cdb = new ConnectionDB();
        String username = lg.username1;
        String studentid = Integer.toString(cdb.id);
        cdb.getUsername(username);
        ComboBoxqry();
        viewTable(viewqry, studentid);
    }//GEN-LAST:event_studentstatusActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        login lg = new login();
        ConnectionDB cdb = new ConnectionDB();
        String username = lg.username1;
        String studentid = Integer.toString(cdb.id);
        cdb.getUsername(username);
        ComboBoxqry();
        viewTable(viewqry, studentid);
     
        
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        changePassword cp = new changePassword();
        cp.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Role rl = new Role();
        rl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl;
    private javax.swing.JLabel studentId;
    private javax.swing.JLabel studentName;
    private javax.swing.JLabel studentSection;
    private javax.swing.JComboBox<String> studentstatus;
    // End of variables declaration//GEN-END:variables
}
