/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package joysis_ams;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JAYCEE
 */
public class Teacher extends javax.swing.JFrame {

    Connection conn = javaconnect.ConnectDB();
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    PreparedStatement pst2 = null;
    ResultSet rs2 = null;
    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        fillTable();
        fillID();
        fillName();
        fillStatus();
        fillDate();
        fillID2();
    }
    
    public void fillTable(){
        try {
            pst = conn.prepareStatement("SELECT * FROM attendance");
            rs = pst.executeQuery();
            
            while(rs.next()) {
                teacherTable.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
        }
    }
    
    private void fillID(){
        try {
            String sql = "SELECT * from attendance";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("student_id");
                idCB.addItem(name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fillName(){
        try {
            String sql = "SELECT * from attendance";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("name");
                nameCB.addItem(name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fillStatus(){
        try {
            String sql = "SELECT * from attendance";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("status");
                statusCB.addItem(name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fillDate(){
        try {
            String sql = "SELECT * from attendance";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("date");
                dateCB.addItem(name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fillID2(){
        try {
            String sql = "SELECT * from student";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("student_id");
                EidCB.addItem(name);
                RidCB.addItem(name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderTF1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        statusCB = new javax.swing.JComboBox<>();
        nameCB = new javax.swing.JComboBox<>();
        idCB = new javax.swing.JComboBox<>();
        dateCB = new javax.swing.JComboBox<>();
        clearFilter = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        AusernameTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ApasswordTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AfirstnameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AmiddlenameTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AlastnameTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AsectionTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AgenderTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        EusernameTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        EfirstnameTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        EmiddlenameTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ElastnameTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        EpasswordTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        EsectionTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        EidCB = new javax.swing.JComboBox<>();
        EgenderTF = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        RusernameTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        RfirstnameTF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        RmiddlenameTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        RlastnameTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        RpasswordTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        RsectionTF = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        RidCB = new javax.swing.JComboBox<>();
        RgenderTF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        removeBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();

        genderTF1.setText("Gender");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Teacher Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Status");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 44, 112, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Student Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 44, 108, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Student ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 44, 81, -1));

        statusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        statusCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCBActionPerformed(evt);
            }
        });
        getContentPane().add(statusCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 72, 112, -1));

        nameCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        nameCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCBActionPerformed(evt);
            }
        });
        getContentPane().add(nameCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 72, 125, -1));

        idCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        idCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCBActionPerformed(evt);
            }
        });
        getContentPane().add(idCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 72, 81, -1));

        dateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        dateCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateCBActionPerformed(evt);
            }
        });
        getContentPane().add(dateCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 72, 108, -1));

        clearFilter.setText("Clear Filter");
        clearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFilterActionPerformed(evt);
            }
        });
        getContentPane().add(clearFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 71, 90, -1));

        AusernameTF.setText("jTextField1");

        jLabel6.setText("Username");

        ApasswordTF.setText("jTextField1");

        jLabel7.setText("Password");

        AfirstnameTF.setText("jTextField1");

        jLabel8.setText("First Name");

        AmiddlenameTF.setText("jTextField1");

        jLabel9.setText("Middle Name");

        AlastnameTF.setText("jTextField1");

        jLabel10.setText("Last Name");

        AsectionTF.setText("jTextField1");

        jLabel12.setText("Section");

        AgenderTF.setText("jTextField1");

        jLabel13.setText("Gender");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AfirstnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AusernameTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApasswordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AmiddlenameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlastnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AsectionTF, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgenderTF, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AusernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AsectionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgenderTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AfirstnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AmiddlenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AlastnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Student", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Student ID");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 19));

        EusernameTF.setText("jTextField1");
        jPanel4.add(EusernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 138, 29));

        jLabel15.setText("Username");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 138, 19));

        EfirstnameTF.setText("jTextField1");
        jPanel4.add(EfirstnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 138, 29));

        jLabel16.setText("First Name");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 138, 19));

        EmiddlenameTF.setText("jTextField1");
        jPanel4.add(EmiddlenameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 92, 138, 29));

        jLabel17.setText("Middle Name");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 67, 138, 19));

        ElastnameTF.setText("jTextField1");
        jPanel4.add(ElastnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 92, 138, 29));

        jLabel18.setText("Last Name");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 67, 138, 19));

        EpasswordTF.setText("jTextField1");
        jPanel4.add(EpasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 138, 29));

        jLabel19.setText("Password");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 138, 19));

        EsectionTF.setText("jTextField1");
        jPanel4.add(EsectionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 138, 29));

        jLabel20.setText("Section");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 138, 19));

        EidCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        EidCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EidCBActionPerformed(evt);
            }
        });
        jPanel4.add(EidCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        EgenderTF.setText("jTextField1");
        jPanel4.add(EgenderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 138, 29));

        jLabel28.setText("Gender");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 138, 19));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel4.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jTabbedPane1.addTab("Edit Student", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Student ID");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 19));

        RusernameTF.setText("jTextField1");
        jPanel5.add(RusernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 138, 29));

        jLabel22.setText("Username");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 138, 19));

        RfirstnameTF.setText("jTextField1");
        jPanel5.add(RfirstnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 138, 29));

        jLabel23.setText("First Name");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 138, 19));

        RmiddlenameTF.setText("jTextField1");
        jPanel5.add(RmiddlenameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 92, 138, 29));

        jLabel24.setText("Middle Name");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 67, 138, 19));

        RlastnameTF.setText("jTextField1");
        jPanel5.add(RlastnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 92, 138, 29));

        jLabel25.setText("Last Name");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 67, 138, 19));

        RpasswordTF.setText("jTextField1");
        jPanel5.add(RpasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 138, 29));

        jLabel26.setText("Password");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 138, 19));

        RsectionTF.setText("jTextField1");
        jPanel5.add(RsectionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 138, 29));

        jLabel27.setText("Section");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 138, 19));

        RidCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        RidCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RidCBActionPerformed(evt);
            }
        });
        jPanel5.add(RidCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        RgenderTF.setText("jTextField1");
        jPanel5.add(RgenderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 138, 29));

        jLabel29.setText("Gender");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 138, 19));

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        jPanel5.add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jTabbedPane1.addTab("Remove Student", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 730, 160));

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(teacherTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 730, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFilterActionPerformed
        // TODO add your handling code here:
        try {
            pst = conn.prepareStatement("SELECT * FROM attendance");
            rs = pst.executeQuery();
            
            if(rs.next()) {
                teacherTable.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_clearFilterActionPerformed

    private void idCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCBActionPerformed
        // TODO add your handling code here:
        try {
            String s = idCB.getSelectedItem().toString();
            pst = conn.prepareStatement("SELECT * FROM attendance WHERE student_id = ?");  
            pst.setString(1, s);
            rs2 = pst.executeQuery();
            teacherTable.setModel(DbUtils.resultSetToTableModel(rs2)); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_idCBActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try {
            String username = AusernameTF.getText();
            String password = ApasswordTF.getText();
            String firstname = AfirstnameTF.getText();
            String middlename = AmiddlenameTF.getText();
            String lastname = AlastnameTF.getText();
            String section = AsectionTF.getText();
            String gender = AgenderTF.getText();
            
            pst = conn.prepareStatement("INSERT INTO student (username,password,firstname,middlename,lastname,section,gender) VALUES (?,?,?,?,?,?,?)");
            pst.setString(1,username);
            pst.setString(2,password);
            pst.setString(3,firstname);
            pst.setString(4,middlename);
            pst.setString(5,lastname);
            pst.setString(6,section);
            pst.setString(7,gender);
            
            int result = pst.executeUpdate();
            
            if (result==1) {
                JOptionPane.showMessageDialog(this, "Student "+username+" Added SUCCESSFULLY!");
            } else {
                JOptionPane.showMessageDialog(this, "Adding Student "+username+" FAILED!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void nameCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCBActionPerformed
        // TODO add your handling code here:
        try {
            String s = nameCB.getSelectedItem().toString();
            pst = conn.prepareStatement("SELECT * FROM attendance WHERE name = ?");  
            pst.setString(1, s);
            rs2 = pst.executeQuery();
            teacherTable.setModel(DbUtils.resultSetToTableModel(rs2)); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_nameCBActionPerformed

    private void statusCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCBActionPerformed
        // TODO add your handling code here:
        try {
            String s = statusCB.getSelectedItem().toString();
            pst = conn.prepareStatement("SELECT * FROM attendance WHERE status = ?");  
            pst.setString(1, s);
            rs2 = pst.executeQuery();
            teacherTable.setModel(DbUtils.resultSetToTableModel(rs2)); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_statusCBActionPerformed

    private void dateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateCBActionPerformed
        // TODO add your handling code here:
        try {
            String s = dateCB.getSelectedItem().toString();
            pst = conn.prepareStatement("SELECT * FROM attendance WHERE date = ?");  
            pst.setString(1, s);
            rs2 = pst.executeQuery();
            teacherTable.setModel(DbUtils.resultSetToTableModel(rs2)); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dateCBActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try {
            String username = EusernameTF.getText();
            String password = EpasswordTF.getText();
            String firstname = EfirstnameTF.getText();
            String middlename = EmiddlenameTF.getText();
            String lastname = ElastnameTF.getText();
            String section = EsectionTF.getText();
            String gender = EgenderTF.getText();
            String id = EidCB.getSelectedItem().toString();
            
            pst = conn.prepareStatement("UPDATE `student` SET `username`=?,`password`=?,`firstname`=?,`middlename`=?,`lastname`=?,`section`=?,`gender`=? WHERE student_id = ?");
            pst.setString(1,username);
            pst.setString(2,password);
            pst.setString(3,firstname);
            pst.setString(4,middlename);
            pst.setString(5,lastname);
            pst.setString(6,section);
            pst.setString(7,gender);
            pst.setString(8,id);
            int result = pst.executeUpdate();
            
            if (result==1) {
                JOptionPane.showMessageDialog(this, username+"'s Information has been Updated!");
            } else {
                JOptionPane.showMessageDialog(this, "Updating "+username+"'s Information Failed!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void EidCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EidCBActionPerformed
        // TODO add your handling code here:
        try {
            pst = conn.prepareStatement("SELECT student_id FROM student");
            rs = pst.executeQuery();
            
            if (rs.next()) {
                String id = EidCB.getSelectedItem().toString();

                pst = conn.prepareStatement("SELECT * FROM student WHERE student_id = ?");
                pst.setString(1, id);
                rs = pst.executeQuery();

                if (rs.next()==true) {
                    EusernameTF.setText(rs.getString("username"));
                    EpasswordTF.setText(rs.getString("password"));
                    EfirstnameTF.setText(rs.getString("firstname"));
                    EmiddlenameTF.setText(rs.getString("middlename"));
                    ElastnameTF.setText(rs.getString("lastname"));
                    EsectionTF.setText(rs.getString("section"));
                    EgenderTF.setText(rs.getString("gender"));
                } else {
                    JOptionPane.showMessageDialog(this, "No Record Found!");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_EidCBActionPerformed

    private void RidCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RidCBActionPerformed
        // TODO add your handling code here:
        try {
            pst = conn.prepareStatement("SELECT student_id FROM student");
            rs = pst.executeQuery();
            
            if (rs.next()) {
                String id = RidCB.getSelectedItem().toString();
            
                pst = conn.prepareStatement("SELECT * FROM student WHERE student_id = ?");
                pst.setString(1, id);
                rs = pst.executeQuery();

                if (rs.next()==true) {
                    RusernameTF.setText(rs.getString("username"));
                    RpasswordTF.setText(rs.getString("password"));
                    RfirstnameTF.setText(rs.getString("firstname"));
                    RmiddlenameTF.setText(rs.getString("middlename"));
                    RlastnameTF.setText(rs.getString("lastname"));
                    RsectionTF.setText(rs.getString("section"));
                    RgenderTF.setText(rs.getString("gender"));
                } else {
                    JOptionPane.showMessageDialog(this, "No Record Found!");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_RidCBActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        try {
            String username = RusernameTF.getText();
            String id = RidCB.getSelectedItem().toString();
            
            pst = conn.prepareStatement("DELETE FROM `student` WHERE student_id = ?");
            pst.setString(1,id);
            int result = pst.executeUpdate();
            
            if (result==1) {
                JOptionPane.showMessageDialog(this, username+"'s Account has been Deleted!");
            } else {
                JOptionPane.showMessageDialog(this, "Deletion of "+username+"'s Account has Failed!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AfirstnameTF;
    private javax.swing.JTextField AgenderTF;
    private javax.swing.JTextField AlastnameTF;
    private javax.swing.JTextField AmiddlenameTF;
    private javax.swing.JTextField ApasswordTF;
    private javax.swing.JTextField AsectionTF;
    private javax.swing.JTextField AusernameTF;
    private javax.swing.JTextField EfirstnameTF;
    private javax.swing.JTextField EgenderTF;
    private javax.swing.JComboBox<String> EidCB;
    private javax.swing.JTextField ElastnameTF;
    private javax.swing.JTextField EmiddlenameTF;
    private javax.swing.JTextField EpasswordTF;
    private javax.swing.JTextField EsectionTF;
    private javax.swing.JTextField EusernameTF;
    private javax.swing.JTextField RfirstnameTF;
    private javax.swing.JTextField RgenderTF;
    private javax.swing.JComboBox<String> RidCB;
    private javax.swing.JTextField RlastnameTF;
    private javax.swing.JTextField RmiddlenameTF;
    private javax.swing.JTextField RpasswordTF;
    private javax.swing.JTextField RsectionTF;
    private javax.swing.JTextField RusernameTF;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearFilter;
    private javax.swing.JComboBox<String> dateCB;
    private javax.swing.JTextField genderTF1;
    private javax.swing.JComboBox<String> idCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> nameCB;
    private javax.swing.JButton removeBtn;
    private javax.swing.JComboBox<String> statusCB;
    private javax.swing.JTable teacherTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
